axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from axf import settings
from home import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^mine/', include('mine.urls', namespace='mine')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^market/', include('market.urls', namespace='market')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # url(r'/$', include('home.urls', namespace='home')),
    url(r'^rest/', include('rest_demo.urls', namespace='rest')),
]

mine/urls.py
from django.conf.urls import url
from mine import views

urlpatterns = [
    url(r'^', views.mine, name='index'),
]

user/urls.py
from django.conf.urls import url
from user import views

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
]

mine/models.py
from django.db import models

# Create your models here.

mine/views.py
from django.shortcuts import render

from user.models import UserModel, OrderModel
from user.views import login_required

# Create your views here.


def mine(request):
    if request.method == 'GET':
        user_id = request.session.get('user_id', None)
        try:
            user = UserModel.objects.get(id=user_id)
        except Exception as e:
            user = None
        if user:
            # 0 待付款， 1 待收货  2 待评价  3 退款/售后
            wait_for_paying = OrderModel.objects.filter(user_id=user_id, o_status=0).count()
            wait_for_receiving = OrderModel.objects.filter(user_id=user_id, o_status=1).count()
            wait_for_evaluating = OrderModel.objects.filter(user_id=user_id, o_status=2).count()
            refund = OrderModel.objects.filter(user_id=user_id, o_status=3).count()
            return render(request, 'mine/mine.html', {'user': user,
                                                      'wait_for_paying': wait_for_paying,
                                                      'wait_for_receiving': wait_for_receiving,
                                                      'wait_for_evaluating': wait_for_evaluating,
                                                      'refund': refund
                                                      })
        return render(request, 'mine/mine.html')

templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/mine.css' %}">
{% endblock %}

{% block EXTJS %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'app/mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="mine">

        <div class="fixed">
            {% if user.username %}
            <!--如果登录，展示头像-->
{#                <img src="/media/{{ user.icon }}" alt="icon">#}
                <img src="{{ user.icon.url }}" alt="icon">
            {% else %}
            <!--或者-->
                <span class="glyphicon glyphicon-user"></span>
            <!--判断结束-->
            {% endif %}
            {% if user.username %}
            <!--如果登录，展示姓名-->
                <p>{{ user.username }}</p>
            {% else %}
            <!--或者展示登录的链接-->
                <p><a href="{% url 'user:login' %}">登录</a></p>
            <!--判断结束-->
            {% endif %}



            <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>

            {% if not user.username %}<!--如果没有登录,展示注册信息-->
                <div id="regis">
                    <a href="">注册</a>
                </div>
            <!--判断结束-->
            {% endif %}

            <p><span class="glyphicon glyphicon-heart"></span><span>收藏</span></p>

        </div>

        <div class="mine">

            <p>我的订单<a href="#">更多&gt;</a></p>

            <div id="nav">

                <ul>
                    <li>
                        <dl>
                            <dt><span id="wait_pay_list" class="glyphicon glyphicon-usd"></span>
                                <span class="badge">
                                    <!--代付款的数量-->
                                    {{  wait_for_paying }}
                                </span></dt>
                            <dd>待付款</dd>
                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span id="order_payed_list" class="glyphicon glyphicon-envelope"></span>
                                <span class="badge">
                                    <!--待收货的数量-->
                                    {{ wait_for_receiving }}
                                </span></dt>
                            <dd>待收货</dd>
                        </dl>

                    </li>

                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-pencil"></span>
                                <span class="badge">
                                    <!--待评价的数量-->
                                    {{ wait_for_evaluating }}
                                </span></dt>
                            <dd>待评价</dd>
                        </dl>

                    </li>

                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-retweet"></span>
                                <span class="badge">
                                    <!--退款/售后的数量-->
                                    {{ refund }}
                                </span></dt>
                            <dd>退款/售后</dd>
                        </dl>

                    </li>

                </ul>

            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                            <span>积分商城</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                            <span>优惠券</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-import"></span></dt>
                            <span>收货地址</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                            <span>客户反馈</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-certificate"></span></dt>
                            <span>关于我们</span>
                        </dl>
                    </li>
                </ul>
            </menu>

            {% if user.username %}
            <!--如果登录了,则退出展示-->
                <p class="logout">
                    <a href="{% url 'user:logout' %}">退出</a>
                </p>
            <!--判断结束-->
            {% endif %}
        </div>
    </div>


{% endblock %}